### ISSUE TITLE
Bad inverted last curves

### ISSUE THREAD

**Issue by 3dodev** [jbuckmccready/CavalierContoursDev#7]
Any idea why the red curve is being produced? It appears as if its the final offset which is an inverted curve that should be disposed. It appears to be programmatically identifiable since it's colored different than the other generated offsets. Is there some reason it remains in the result and is not disposed? 

![extra curve 2](https://user-images.githubusercontent.com/75230855/100695023-528f5680-335e-11eb-817c-4e8ad32b364c.png)
![extra curve](https://user-images.githubusercontent.com/75230855/100694945-2673d580-335e-11eb-8211-7c27f7723d28.png)

**Comment by jbuckmccready** [comment]
Those are purposely added in and colored red for debugging purposes (they are not valid offsets, they are the last raw offsets that were pruned). See this line [here](https://github.com/jbuckmccready/CavalierContoursDev/blob/master/interactiveui/plineoffsetalgorithmview.cpp#L618). It was left over from debugging.

I added a flag and checkbox to toggle it on and off for debugging. See commit: https://github.com/jbuckmccready/CavalierContoursDev/commit/b2988e12294b1e7ca99dfa2cdd3724b06d535cd4
